# This workflow will execute some static analysis tools on the pushed code with Maven

name: Static Analysis with Maven Plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: cache
        uses: actions/cache@v3
        env:
          cache-nanme: cache-checkstyle
        with:
          path: .
          key: ${{ runner.os }}--${{ env.cache-name }}
      - name: Run checkstyle
        run: |
          mvn -B checkstyle:check
          ls
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: gameengine/target/checkstyle-result.xml